### ISSUE TITLE
(MAINTENANCE) adding VIP invites to VIP zone sponsor

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#110]
@az sponsor (FedEX) ma zapewniony benefit _Distribution of guest passes to your clients (up to 50-100). Registration with a special code provided by the Organizer. All registered attendees will be handled as VIP guests_

myślę, że najłatwiej będzie po prostu dodać im 50 zapek w panelu

**Comment by az** [comment]
@KarolinaTEH tylko to...nie wyobrazam sobie zebym cos mial last minute robic co nie bylo wczesniej uzgodnione

**Comment by az** [comment]
zapki dodane ale nie widac zeby bylo ich wiecej w panelu fedexa....musze sprawdzic WTF.

**Comment by az** [comment]
fixed
