### ISSUE TITLE
(TRANSLATION) vips prize

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#128]
re: https://github.com/ecommerceberlin/exhibitors/issues/119

![expojuicer master 2023-02-02 15-28-30](https://user-images.githubusercontent.com/2198/216351891-397fa8e4-dec2-4d43-ab0b-118f2594e1df.png)

prośba o tłumaczenie także na account TEHowym

**Comment by KarolinaTEH** [comment]
done
