### ISSUE TITLE
(EMAIL) Send promoninja emails

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/exhibitors#13]
Please send promoninja intro emails. Subjects:

ENG: E-commerce Berlin Expo - Exhibitor Contest is live!
DE: E-commerce Berlin Expo - Exhibitor Contest ist live!

[ebe-6-promoninja-intro.zip](https://github.com/ecommerceberlin/exhibitors/files/8450769/ebe-6-promoninja-intro.zip)

**Comment by az** [comment]
sent
