### ISSUE TITLE
(TRANSLATION) P2C RSVP reminder

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#131]
@KarolinaTEH chcałbym rozesłać remindery re zapki P2C (dokończyłem skrypt) - idealnie tak do 13:00

prośba o wygładzenie wersji EN i dodanie DE

```
@component('mail::message')
 
Hello,

In the Exhibitor's Panel there are waiting meetng requests from participants of upcoming E-commerce Berlin Expo.

Invitations were sent by your Exhibitor's public profile.

Please RSVP to avoid further reminders.

**Accepting meeting request reveals the Participant's contact details ** 

@component('mail::button', ['url' => $url])
Sign up to check meeting requests
@endcomponent

If you want to receive more incoming meeting requests and reveal contact details - promote your public exhibitor's profile URL ... There are promotional ready-to-use promotional materials URL2

regards,

{{$footer}}

@endcomponent
```

**Comment by klaudia2209** [comment]
GERMAN: 

SUBJECT: Neue Termineinladungen warten auf deiner Ausstellerplattform.

```

@component('mail::message')
 
Hallo,

Du hast auf deiner Ausstellerplattform Terminanfragen von den Teilnehmern der E-Commerce Berlin Expo erhalten. Diese warten auf deine Antwort.

**Hinweis: Durch die Annahme der Terminanfrage werden die Kontaktdaten der Teilnehmer angezeigt.**

@component('mail::button', ['url' => $url])
Siehe Termineinladungen hier
@endcomponent

Um mehr Terminanfragen zu erhalten und eure Präsenz zu erhöhen, teile euer öffentliches Ausstellerprofil (URL) mit anderen. Hier findest du gebrauchsfertige Werbematerialien, die dir dabei nützlich sein können (URL2).

Viele Grüße,

{{$footer}}

@endcomponent

```

**Comment by az** [comment]
@klaudia2209 perfect... dzięki :)

**Comment by az** [comment]
@klaudia2209 dlaczego jest zmieniany sens w cos co nie jest zgodne z prawdą ?  jeśli osoba która dokonuje tłumaczenia nie zna panelu to musi go znać osoba, która akceptuje i postuje tutaj tłumaczenia 

> **Note: Accepting the meeting request will reveal contact information to the participant.** 

nie ma to nic wspólnego ze stanem faktycznym

cc @KarolinaTEH

**Comment by az** [comment]
@klaudia2209 

> Please respond to these requests to avoid further reminders.

dlaczego tego nie ma w wersji DE?

**Comment by klaudia2209** [comment]
W treści wysłanej przez Ciebie jest zdanie: 

"**Accepting meeting request reveals the Participant's contact details ** 

więc zakładałam, że tak miało być. 

DE - dodamy to zdanie

**Comment by az** [comment]
@klaudia2209 

Accepting meeting request reveals the Participant's contact details 
= akceptacja requesta odkrywa dane kontaktowe uczestnika

**to nie jest to samo co**

Accepting the meeting request will reveal contact information to the participant
= Akceptacja requesta odkryje Partipantowi dane kontaktowe

**Comment by klaudia2209** [comment]
Ok, dobrze, zaszła pomyłka, przekażę
