### ISSUE TITLE
Review exhibitors' about + products sections 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#134]
![E-commerce Berlin Expo invites you to a meeting at the E-commerce Berlin Expo 2023-02-09 14-22-59](https://user-images.githubusercontent.com/2198/217824533-1ee882b0-603f-4b9c-b509-33aabede5784.jpg)

@KarolinaTEH chyba w interesie eventu jak i naszym byloby zeby przeklikac wszystkie profile i zobaczyc gdzies jest "ku..." 

bo ktos tam podniosl larum ze sie nie pokazuje markdown...no to teraz sie pokazuje ale nie pokazuje sie HTML

trzeby przejrzec wszystko (w sensie skoordynowac :) i albo dana osoba robi liste gdzie trzeba to poprawic albo od razu poprawia (wchodzi do panelu i reformatuje korzystajac z markdown)..... albo lista i podbitka do firm wedlug przynaleznosci AM-firma

**Comment by klaudia2209** [comment]
dzisiaj rozmawialiśmy o tym z AM i będą sprawdzać profile i poprawiać, tam gdzie trzeba

**Comment by az** [comment]
@klaudia2209 extra...tak zdecydowanie będzie najszybciej (chyba że skala zjawiska okaże się przygniatająca :)

**Comment by klaudia2209** [comment]
mam nadzieję, że dadzą radę ;)

**Comment by az** [comment]
@klaudia2209 jaki status? / cc @KarolinaTEH

**Comment by klaudia2209** [comment]
dostałam info, że sprawdzili wszystkie profile i jest ok
