### ISSUE TITLE
(EMAIL) promoninja contest - to be sent 13.02

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#135]
ENGLISH
SUBJECTS (to choose): 
- Make the most of the Contest - 7 Days left 
- Alert! We are worried about your participation in the fair... low engagement in traffic driving, lead generation, and boosting your Exhibitor Profile

```
@component('mail::message')
 
# Hello {{ array_get($profile, "fname")  }},

@component('mail::panel')

With just 7 days remaining until the contest deadline, it's crucial to make the most of this opportunity. 

To maximize your chances of success, we strongly encourage you to start sending VIP Invitations to your important partners and potential clients to attend the Expo and give them access to the exclusive VIP Zone with comfortable seating and refreshments. 

In the meantime, make sure to not forget about your RSVP’s and pending invitations otherwise, you might miss on some leads!

<LINK>

If you're running low on points, promoting your participation on social media is a great way to get more. Share your participation and receive rewards!

<PROMOTIONAL ACTIVITIES LINK>

Here's to a successful experience!
EBE Team
```

**Comment by klaudia2209** [comment]
GERMAN:

SUBJECT: Mach das Beste aus dem Wettbewerb – 7 Tage übrig

```
Warnung! Wir machen uns Sorgen über deine Teilnahme bei der Expo... geringes Engagement im Traffic, Leads Generierung, Stärkung des Ausstellerprofils.

Nur noch 7 Tage bis zum Wettbewerbstermin. Es ist wichtig, dass du diese Gelegenheit nutzt.

Um deine Chancen auf Erfolg zu maximieren, empfehlen wir dir, VIP-Einladungen zu versenden. Lade deine wichtigen Partner und potenziellen Kunden ein und gib ihnen Zugang zur exklusiven VIP-Zone mit bequemen Sitzmöglichkeiten und Erfrischungen.

Vergiss nicht deine RSVPs und noch ausstehende Einladungen, denn du möchtest keine Leads verpassen.

<LINK>

Wenn du wenig Punkte hast, dann verbreite deine Teilnahme einfach in den Sozialen Medien. Teile deine Teilnahme und erhalte Belohnungen!

<PROMOTIONAL ACTIVITIES LINK>

Auf eine erfolgreiche Erfahrung!
EBE Team

```

**Comment by peterecommberlin** [comment]
Adam, to były alternatywne tematy!


Alert! We are worried about your participation in the fair... low engagement in traffic driving, lead generation, and boosting your Exhibitor Profile


Warnung! Wir machen uns Sorgen über deine Teilnahme bei der Expo... geringes Engagement im Traffic, Leads Generierung, Stärkung des Ausstellerprofils.

**Comment by az** [comment]
@klaudia2209 @peterecommberlin "to be sent 13.02" - jakie substancje odurzające są rozdawane w biurze? :)

**Comment by klaudia2209** [comment]
wiem, z naszej winy wynika to opóźnienie, bo dostarczyliśmy za późno content

**Comment by az** [comment]
@klaudia2209 @peterecommberlin zrobilem jednak swoja wizje swiata na podstawie poprzedniego (bo zapki szly we wtorek)..... a juz pomijac to to wydaje mi sie ze tresc byla chaotyczna.... wspomnienie o konkursie (bez info jak to poprawic, kto prowadzi) a pozniej nagle z dupy VIPy ( ktore nie maja nic wspolnego z konkursem) i powrot do materialow promo....

ten caly proces cotentowy jest bez sensu..... przyszlosciowo (o ile pozwola na to zmiany osobowe po stronie TEH) bedziemy to ogarniac sami i zlecac tylko "touchup" en + tlumaczenie de....

cc @KarolinaTEH

**Comment by klaudia2209** [comment]
ok, dobrze, dzięki za info!
