### ISSUE TITLE
(EMAIL) content - SCANNER - to be sent 22.02

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#137]
SUBJECT: Discover the Easiest Way to Collect Contact Details at the Expo

```
@component('mail::message')

# Hi {{ array_get($profile, "fname") }}, 

We’ve prepared something special for you! At the Expo, you can easily collect the contact details of the visitors you meet there. It's effortless; we have prepared a step by step instruction for you in your Exhibitor's Panel.

@component('mail::button', ['url' => $accountUrlBadgescanner])
Scanner Manual
@endcomponent

Please note that when you open [expojuicer.com](http://expojuicer.com) on your phone, be sure to select your company name. **This is crucial to ensure that the contact details are saved to your profile.**

All the contact details you collect will be immediately saved in the *Scanned leads* section of your Exhibitor's panel. To view all the contact information and comments, please use the export function.

If you have any questions, please don't hesitate to ask!

Best Regards,

{{$footer}}

@endcomponent

```

**Comment by KarolinaTEH** [comment]
DE SUBJECT: Entdecke den einfachsten Weg, um Kontaktdaten auf der Expo zu sammeln

```
@component('mail::message')

# Hallo {{ array_get($profile, "fname") }},

Wir haben etwas Besonderes für dich vorbereitet! Auf der Expo kannst du mühelos die Kontaktdaten der Besucher sammeln, die du dort triffst. Es ist sehr einfach; Einen Schritt-für-Schritt-Anleitung haben wir für dich in deinem Aussteller-Panel vorbereitet.

@component('mail::button', ['url' => $accountUrlBadgescanner])
Scannen Anweisung
@endcomponent

Bitte beachte, dass du bei der Öffnung von [expojuicer.com](http://expojuicer.com) unbedingt deinen Firmennamen auswählst. **Dies ist entscheidend, um sicherzustellen, dass die Kontaktinformationen in deinem Profil gespeichert werden.**

Alle von dir gesammelten Kontaktinformationen werden sofort im Abschnitt *Gescannte Leads* deines Aussteller-Panels gespeichert. Um alle Kontaktdaten und Kommentare zu sehen, nutze bitte die Exportfunktion.

Wenn du Fragen hast, zögere bitte nicht, uns zu kontaktieren!

Herzliche Grüße,

{{$footer}}

@endcomponent

```

**Comment by az** [comment]
@KarolinaTEH wywalilem zdania z linkiem do expoj.... 

* przede wszystkim dublowanie tutorali jest bez sensu... jesli tutorial ma niedokladne info to trzeba poprawic tutorial
* druga rzecz ze byloby rozyko ze odpala te strone (expojuicer) na desktopie i nie beda wiedzieci co dalej
* trzecia rzecz ze zdanie nie jest prawdziwe.... jesli ktos od razu zacznie skanowac to wyskakuje mu WHO ARE YOU? i musi sie zalogowac tak czy siak (skanowania nie straci)

**Comment by KarolinaTEH** [comment]
@az true, ale na TEH był tylko link do tutorialu i wystawcy przychodzili (nie był to pojedynczy przypadek), że wyświetla im się 'lista z jakimiś nazwami' i nie wiedzą co mają z nią zrobić. W kilku przypadkach myśleli, że mają wybrać nazwę firmy skanowanej osoby, dlatego pomyślalam, że lepiej dać to dodatkowo w treści i zaznaczyć, że to ważne 
anyway - poprawiłam tutorial

tak - jeśli ktoś zacznie skanować to wyskoczy mu możliwość wyboru firmy, ale w tutorialu imo lepiej dać jedną wersję zdarzeń

**Comment by az** [comment]
@KarolinaTEH poprawilas tutorial i to jest dobry kierunek - dzieki..... gdyby w tresci bylo ze maja otworzyc expojuicera na komorce ktora beda skanowac a nie na urzadzeniu na ktorym czytaja mejla to pewnie bym puscil.... 
wiecej niz 2 linki w tresci to generalnie zly kierunek bo moga odpalic drugi i juz tutoriala nie zobacza :)
