### ISSUE TITLE
(MAINTENANCE) /badgescanner mockup change

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#139]
@az prośba o podmianę mockupa w instrukcji: https://account.ecommerceberlin.com/#/badgescanner

![howto_step_03](https://user-images.githubusercontent.com/80756258/220083018-e2cd5669-d809-4563-a8c7-52dad91c74c8.png)
[howto_step_03.pdf](https://github.com/ecommerceberlin/exhibitors/files/10783495/howto_step_03.pdf)

**Comment by az** [comment]
@KarolinaTEH have you updated that maybe? :)

**Comment by KarolinaTEH** [comment]
not yet, but it's on my list to be done before Monday's mailing
