### ISSUE TITLE
(EMAIL) survey ping

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#144]
@az 
lista ID do wykluczeń:
1684
1926
1586
2194 
1880
2150 
2078
2264
1496
2154
2195
1790
1068

jak będziesz miał wersję ENG to poproszę Dominika o szybkie tłumaczenie

(idea) temat może związany z pytaniem o 2-dniowy event? imo może to zainteresować

**Comment by az** [comment]
@KarolinaTEH puszczam to samo poki co.... re 2 dniowy event super pomysl - to poprosze subjecty EN+DE

**Comment by KarolinaTEH** [comment]
Are you ready for a 2-days Expo? Let us know!

Seid ihr bereit für ein 2-tägiges Event? Gibt uns Bescheid!

**Comment by az** [comment]
sent

**Comment by az** [comment]
@KarolinaTEH pewnie jeszcze bedzie 1 podbitka.... przyszlosciowo zawsze mi wrzucaj w komentarzu pelna aktualna liste w formacie 

1684,1926,1586,2194,1880,2150,2078,2264,1496,2154,2195,1790,1068,1373,2058

danke
