### ISSUE TITLE
(QUESTION) browse participants: hide visitors with specific participant_type

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#181]
would it be possible to exclude:
- developer
- consultant
- student
from the list? (entire list, not just filters)

**Comment by az** [comment]
@KarolinaTEH in the future maybe... not before the event .... but i assume the ideas is to hide some registrations so we may choose default (pre-selected) option like retailer - let me know if you want to proceed this way.....

**Comment by KarolinaTEH** [comment]
@az sure, it'd work as well, thanks
so _retailer_wholesaler_ option should be pre-selected

**Comment by az** [comment]
added
