### ISSUE TITLE
(MAINTENANCE) checks before PromoNinja start (25.01)

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#183]
from my side, I'll: 
- update the graphics on Monday
- create PR with revelant tab revealing in the panel on on Thursday

**Comment by az** [comment]
@KarolinaTEH OK,
we are now using https://fingerprint.com/ instead google analytics... i will re-configure it for EBE.... it costs 200USD/month... EC will be invoiced :)
