### ISSUE TITLE
(BUG) browse participants: company_role filter not functioning

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#184]
**expected result**: display results according to the selected filter

**actual result**: results are not filtered (participant_type filter works correctly)

<img width="1057" alt="image" src="https://github.com/ecommerceberlin/exhibitors/assets/80756258/ecb4bc14-f953-47ea-844b-e529a9c17f39">

<img width="986" alt="image" src="https://github.com/ecommerceberlin/exhibitors/assets/80756258/e72abecb-6c56-4f30-9398-473a3dacf0da">

**Comment by az** [comment]
@KarolinaTEH 

https://github.com/ecommerceberlin/exhibitors/issues/177 do not duplicate  read comments please .... and mind that linked issue is not yet closed (+feature is not public)
