### ISSUE TITLE
(MAINTENANCE) update promoninja prizes

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#187]
**out:** 
video_interview
rollups
earlybird 

**left:**
meetups
vip
blog 
brand_highlight (maximum position: 1 instead of 4)
leaflets

**Comment by az** [comment]
![ eventjuicer_promo_prizes | phpMyAdmin 4 8 3 2024-01-23 11-57-53](https://github.com/ecommerceberlin/exhibitors/assets/2198/cb5aca01-8c75-44ca-aaf7-4b9285782351)

after an update - please confirm its OK @KarolinaTEH

**Comment by KarolinaTEH** [comment]
thanks, 
just one thing - meetups:
- max: 300 (as agreed with PS it should not be limited)
- level: 20 (50 invitations for the first 20 points)

**Comment by az** [comment]
max: 300 - OK

"level: 20 (50 invitations for the first 20 points)"

does Peter know that we have different solution for counting views? (via fingerprinting library)?

i would wait with that decision till:

* we see if we would have better visitor RSVP panel (sending invites and not having responses is worse that not sending invites)
* check the dynamics with new pageviews counting solution 

another thing is that they see (without imiting) LINKEDIN profiles so...they may try to use it and we do not have to pollute communication on our side

one can always change some parameteres during the contest and it is nice motif to another reminder msg

**Comment by az** [comment]
related https://github.com/ecommerceberlin/exhibitors/issues/183

**Comment by KarolinaTEH** [comment]
yes, he knows.
level: ok - totally understand. So I'll adjust translations (delete the 20 points part)

**Comment by az** [comment]
btw: .... that linkedin profiles and company_role should be accessible as a "prize" for (even micro-engaged ones)... what do you think? 
we could add another prize like "profiled list of visitors".... and that could be accessible for those with min 20pts :)

**Comment by az** [comment]
participation_type could stay as a standard ofcoz....

**Comment by KarolinaTEH** [comment]
sounds like a good idea. I'll just talk it through in a minute with Mark and Peter

**Comment by az** [comment]
yep... we always looked for more virtual prizes and it seems perfect fit for this purpose .... 
for company_role the would see the label "click here for position info" (info how to get it via overlay).... for LI they would get an overlay with the info how to make it visible....also the company_role filtering would be disabled

**Comment by KarolinaTEH** [comment]
ok, so we came to the conclusion that it'd be really difficult to communicate.
exhibitors were not eager to use this tool before and blocking 2 features would not make it easier to convince them to do so

but we could just hide linkedin, leaving filters visible for everyone -> easy to communicate and not that confusing for exhb
