### ISSUE TITLE
(EMAIL) PromoNinja ping - to be sent 12.02

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#193]
information from the ranking (leaders) is going to be included in the content, so I'll update this comment and create PR on 12/02
Subject: 
EN: Urgent: Final days to use VIP tickets and schedule your meetings!
DE: Dringend: Noch ein paar Tage, um VIP-Tickets zu nutzen und Termine zu vereinbaren!

File: to be updated
(content for review is available here: https://docs.google.com/document/d/1tmcLf74Elxys1mHxcWcZtCD4fq0ijEo0dklPIzipTeQ/edit)

**Comment by KarolinaTEH** [comment]
@az can you please let me know which companies are the top 3 distributors of VIP invitations?

**Comment by az** [comment]
<img width="307" alt=" eventjuicer_company_vipcodes | phpMyAdmin 4 8 3 2024-02-12 10-17-00" src="https://github.com/ecommerceberlin/exhibitors/assets/2198/d33a318a-1a16-4fff-9920-1892cef894f8">

**Comment by az** [comment]
`SELECT `company_id`, COUNT(*) AS count  FROM `eventjuicer_company_vipcodes` WHERE `event_id` = 100 AND `participant_id` > 0 GROUP BY `company_id` ORDER BY `count`  DESC`

**Comment by KarolinaTEH** [comment]
File: 
ebe8-promoninja-warning-en.blade.php
ebe8-promoninja-warning-de.blade.php
