### ISSUE TITLE
(EMAIL) logistics - to be sent 15.02

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#195]
Subject: 
EN: Get Ready for EBE 2024: Your Exhibitor’s Guide to the E-commerce Berlin Expo
DE: Mach dich bereit für die EBE 2024: Dein Ausstellerleitfaden für die E-Commerce Berlin Expo

FIle:
EN: ebe8-logistics-final-en.blade.php
DE: ebe8-logistics-final-de.blade.php

Recipient: all reps

**Comment by az** [comment]
@KarolinaTEH 

"Recipient: all reps"?

this should be handled by EBE staff ... i cannot find any traces of sending bilingual emails to REPS (have you found it in commands***?) 

re: communication with reps - i have always exported CSV from an admin and sent SMSes strictly before  an event (TEH only)

**Comment by KarolinaTEH** [comment]
ok, I hadn't thought about that

**Comment by az** [comment]
i am sorry for not catching this earlier...maybe we need to put some code for recipients in the subject?

**Comment by KarolinaTEH** [comment]
sure, so for now we have:
- main contact person - receives all emails - no additional info 
- sales manager 
- event manager 
- pr manager 
- all of the above - all
eg. (EMAIL) logistics - to be sent 15.02 (all)

**Comment by az** [comment]
yep... re reps i can only send email to above context regarding meetups, reps status (low - below threshold - volume)
