### ISSUE TITLE
rethink differences in logistics timeline

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#2]
setting file is here (cmd+f "logistics")

https://raw.githubusercontent.com/ecommerceberlin/exhibitors/main/src/settings.js

**Comment by az** [comment]
@jprzybylski4 would be nice to have it before monday. thx

**Comment by jprzybylski4** [comment]
@az EBE timeline
[settings.js.zip](https://github.com/ecommerceberlin/exhibitors/files/8694831/settings.js.zip)

**Comment by jprzybylski4** [comment]
As I'm not 100% sure I've done everything right here is the timeline copy:
1. RIGHT AFTER THE BOOKING
Check your company profile
Structure the communication channels
Consider additional sponsoring
2. 3 MONTHS BEFORE
Arrange your stand
3. 2 MONTHS BEFORE
Register company representatives
Promote your company
Arrange your stand - DEADLINE
4. ONE MONTH BEFORE
Register company reps - DEADLINE
Promote your company
Order additional vouchers (EGA Gala)
5. THREE WEEKS
Promote your company - DEADLINE
Arrange meetings with participants
Invite VIPs?
Order additional vouchers (EGA Gala) - DEADLINE
6. TWO WEEKS
Arrange meetings with participants
Ship your materials to the venue
7. ONE WEEK
Arrange meetings with participants - DEADLINE
Ship your materials to the venue - DEADLINE

**Comment by jprzybylski4** [comment]
@az just wanted to follow up and check if you can provide any ETA when you might have time to work on nextgen for EBE?

**Comment by az** [comment]
@jprzybylski4 cannot provide ETA... i do hope to jump into this BEFORE September but time will tell.
