### ISSUE TITLE
(EMAIL) photos + survey ping

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#203]
Subject:
EN: Get your PHOTOS from the Expo | Fill in the post-event survey
DE: Fülle den Fragebogen aus und lade dir deine Bilder von der Expo runter!

FIle:
EN: [ebe8-photos-en.blade.php](https://github.com/KarolinaTEH/services/blob/master/resources/views/emails/company/ebe8-photos-en.blade.php)
DE: [ebe8-photos-de.blade.php](https://github.com/KarolinaTEH/services/blob/master/resources/views/emails/company/ebe8-photos-de.blade.php)

**Comment by KarolinaTEH** [comment]
photos are ready, downloading works 
eg https://photos.ecommerceberlin.com/1111/ebe8

**Comment by az** [comment]
i will try to send tomorrow
