### ISSUE TITLE
(EMAIL) premium services - to be sent 19.08 (current exhibitors)

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#212]
Subject:
EN: Maximise your visibility at E-commerce Berlin Expo 2025 with Exclusive Sponsorships
DE: Maximiere deine Sichtbarkeit auf der E-commerce Berlin Expo 2025 mit exklusiven Sponsoring-Optionen

FIle: 
EN: [ebe9-premium-services-en.blade.php](https://github.com/eventjuicer/services/pull/56/commits/59ef61d6c7f90a1321a0a09714b7c7f533e4e5b8#diff-110876aaac10ddfa73c2a6d6b934e4cd5741743b7a42d81d4d9f11a23053f5da)
DE: [ebe9-premium-services-de.blade.php](https://github.com/eventjuicer/services/pull/56/commits/59ef61d6c7f90a1321a0a09714b7c7f533e4e5b8#diff-07f169b20fd6c4635fa25e2ebb09b108e078fe7a004342abbbbaedb3dd74109e)

Adam, if possible, please exclude Noel's companies from this mailing. He is ooo, and his emails will be sent later manually

Calendly links:
Marianna: https://calendly.com/marianna-bachanek/ebe25-onboarding-meeting
Dominik: https://calendly.com/dominik-ebe/exhibitor-meeting

**Comment by KarolinaTEH** [comment]
@az today’s/tomorrow’s mailing. 
please let me know when you’re planning to send it out

**Comment by az** [comment]
@KarolinaTEH in 15 minutes
