### ISSUE TITLE
(EMAIL) additional services - to be sent 14.11

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#216]
Subject:
EN: Haven't started planning the set-up of your space yet? Order a stand construction from us now!
DE: Noch nicht mit der Standgestaltung begonnen? Bestelle einen Standbau bei uns jetzt! 

FIle:
EN: [ebe9-additional-services-en.blade.php](https://github.com/eventjuicer/services/commit/000a8542324ec709ec371f250957c42ebc2f745f#diff-edc87d9b9924d406c246e9eb45ed59eb86afa8057e1afe234d077e9cf61f06b7)
DE: [ebe9-additional-services-de.blade.php](https://github.com/eventjuicer/services/commit/000a8542324ec709ec371f250957c42ebc2f745f#diff-0a2cea6e5fe7cee48e699e6195f62a27ea29904e9721024db48ebf73315096f0)

**Comment by az** [comment]
@KarolinaTEH such emails are BAD...we should not point to items where authentication is required

**Comment by az** [comment]
@KarolinaTEH mods - https://github.com/eventjuicer/services/commit/e9325740c0969a47bbe9a4e2f0718ea602dd3b8c

**Comment by KarolinaTEH** [comment]
I know - I talked it over with AMs, and the decision was that it's an important point that can't be skipped (knowing the risks)
