### ISSUE TITLE
photos of account managers

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#3]
@jprzybylski4 i need it for the support widget (now we have static - based on settings... new will be dynamic)

**Comment by jprzybylski4** [comment]
Working on it - should have all the photos by Monday

**Comment by jprzybylski4** [comment]
Marta Masternak - https://res.cloudinary.com/ecommerceberlin/image/upload/v1636370755/Awards%20website/marta.png
Dominik Kleina - https://res.cloudinary.com/ecommerceberlin/image/upload/v1648629512/Exhibitors/expojuicer/Dominik_Kleina.jpg
Gerome Yalim - https://res.cloudinary.com/ecommerceberlin/image/upload/v1648629534/Exhibitors/expojuicer/Gerome_Yalim.jpg
