### ISSUE TITLE
provide AM contact data AND photos

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#34]
i need:

1) contact info for Adem and Marianna

2) URLs to cloudinary images showing their faces

**Comment by az** [comment]
https://github.com/ecommerceberlin/ecommerceberlin.com/issues/227

**Comment by peterecommberlin** [comment]
Marianna Bachanek
marianna@ecommerceberlin.com
+49 30 2555 9875 (j.w - czekam za nowym numerem Zadarmy)
https://res.cloudinary.com/ecommerceberlin/image/upload/v1668515194/Website/image0_1.jpg 

Adem Özkara
adem@ecommerceberlin.com
+49 30 2555 9875
https://res.cloudinary.com/ecommerceberlin/image/upload/v1668515190/Website/IMG_5094.jpg
