### ISSUE TITLE
(EMAIL) send upgrades/arrangement email 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#37]
re https://github.com/ecommerceberlin/exhibitors/issues/36

**Comment by az** [comment]
![adamzygadlewicz — ssh -l root 138 201 199 47 — 190×71 2022-11-18 11-34-40](https://user-images.githubusercontent.com/2198/202683291-dac078e0-4351-4fb2-a00c-3a8634ec56b3.jpg)

errors @peterecommberlin @klaudia2209

**Comment by az** [comment]
No company assigned for xxxx@billie.io - skipped.

**Comment by az** [comment]
(DE) errors
![adamzygadlewicz — ssh -l root 138 201 199 47 — 190×71 2022-11-18 11-37-14](https://user-images.githubusercontent.com/2198/202687340-20ba7958-23fd-48ed-be67-7c1914dd4be0.jpg)

**Comment by klaudia2209** [comment]
done by @peterecommberlin
