### ISSUE TITLE
internal ticket is visible in the booth arrangement section 

### ISSUE THREAD

**Issue by peterecommberlin** [ecommerceberlin/exhibitors#38]
I created a counter ticket in the system for internal use only. We don't want to offer this service to the clients (low profit). 
This service shouldn't be visible in the exhibitors' profile but... it is. I have no idea how it's connected to the website... See the screenshots below:

TICKET
![Screenshot 2022-11-22 at 10 42 11](https://user-images.githubusercontent.com/35766428/203281349-fbf53f07-9e77-4d07-83dc-d3412735768b.png)

**OLD account** 

![Screenshot 2022-11-22 at 10 41 44](https://user-images.githubusercontent.com/35766428/203281394-fd687ee0-9367-4144-a4ff-10c977c6aec0.png)

PARTICIPANT PROFILE

![Screenshot 2022-11-22 at 10 40 50](https://user-images.githubusercontent.com/35766428/203281429-de197592-ef55-4253-891d-c4e3bf0fe802.png)

Help!

**Comment by az** [comment]
![tickets 2022-11-22 14-20-00](https://user-images.githubusercontent.com/2198/203324303-23f9c8e5-fa6b-4a95-9c1f-f0c4919dd4f0.jpg)
@peterecommberlin you have 2 tickets names "counter" - the second one had the option "service_external" set - which caused it to appear
