### ISSUE TITLE
(EMAIL) + QUESTIONS - ADDITIONAL SERVICES - to be sent 13.12 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#42]
Hello @az, 

here is another system mail to send, based on: 

- EN: https://github.com/eventjuicer/services/blob/master/resources/views/emails/company/ebe6-additional-services-2-en.blade.php 
- DE: https://github.com/eventjuicer/services/blob/master/resources/views/emails/company/ebe6-additional-services-2-de.blade.php 

**ENGLISH VERSION** - changes begin after "hello" 

We would like to kindly remind you about the possibility of ordering additional services for your stand with us. 

Please double check if you have everything you need in your package, otherwise you may take a look at our range of additional services. 

It’s highly recommended to place all the orders before the Christmas holidays so we can process everything much smoother.

**You can still order services, such as:**
​
* Complete booth arrangement 
* Carpet equipment
* 50 inch LED display
* Foldable brochure rack 
* Additional electricity connection

**GERMAN VERSION** - changes begin after "hallo" 

Wir möchten dich nochmals an die Möglichkeit erinnern, bei uns zusätzliche Standdienste zu bestellen. 

Bitte stell noch einmal sicher, dass ihr im Paket alles habt, was ihr braucht, sonst könnt ihr euch noch unser Angebot an Extraservices anschauen. 
 
Es ist empfehlenswert, Bestellungen noch vor den Weihnachtsfeiertagen aufzugeben, damit die Abwicklung reibungslos abläuft.

**Es ist die letzte Chance, die folgenden Standdienste zu buchen:**
​
* Vollständiger Standbau
​* Teppichbelag
* LED-Bildschirm 50 Zoll
* Broschürenhalter
* Zusätzliche Stromleistung
_________________

* Publishing date: 13.12 (next Tuesday), it would be perfect to send it by particular account managers

* Can we add the link: https://account.ecommerceberlin.com/#/logistics?arrangement under the words: 
EN: have everything you need in your package 
DE: dass ihr im Paket alles habt, was ihr braucht 

* We would like to exclude the companies who already have the booths ordered. We will deliver the list on Monday. 

* We would like to send the emails as DK, AO, MB.

**Comment by az** [comment]
@klaudia2209 subjects? you ALWAYS forget about it

**Comment by az** [comment]
![EventJuicer 🔊 2022-12-13 13-12-39](https://user-images.githubusercontent.com/2198/207314939-b608e502-7db8-4a77-8751-7eb6eb4d6aa1.jpg) @peterecommberlin @klaudia2209 ALWAYS check company-AM assignments before upcoming deployment of campaign

**Comment by klaudia2209** [comment]
@az 

- SUBJECT:
EN: Booth arrangement order - reminder
DE: Standbau - kurze Erinnerung

- checking if exhibitors have assigned companies ("old admin") - DONE 
- checking whether AM are assigned to the companies ("new admin") - DONE

**Comment by az** [comment]
excluded IDs 

"1759,2120,1910,1716,2088,2081,2188,2203,1667,2180,2086,1402,2212,2205,2194,2193,2196,2206,2195,2029,1644,2184,1576,1954,2079,2207,2124,2055,1930,2138,2214,2095,1957,2130,2223,2140,1977,2150,2251,2187,1048,2167,1914,2133,2250,1382,1851,2252,1790,2131,1649,1722,2078,2029,2244,1831,1926"

**Comment by az** [comment]
```
php artisan exhibitors:current-event --defaultlang=en --domain=ecommerceberlin.com --lang=en --subject="Booth arrangement order - reminder" --email=ebe7-additional-services-2 --exclude_company_ids="1759,2120,1910,1716,2088,2081,2188,2203,1667,2180,2086,1402,2212,2205,2194,2193,2196,2206,2195,2029,1644,2184,1576,1954,2079,2207,2124,2055,1930,2138,2214,2095,1957,2130,2223,2140,1977,2150,2251,2187,1048,2167,1914,2133,2250,1382,1851,2252,1790,2131,1649,1722,2078,2029,2244,1831,1926,1058,2254,2201,2222"

php artisan exhibitors:current-event --defaultlang=en --domain=ecommerceberlin.com --lang=de --subject="Standbau - kurze Erinnerung" --email=ebe7-additional-services-2 --exclude_company_ids="1759,2120,1910,1716,2088,2081,2188,2203,1667,2180,2086,1402,2212,2205,2194,2193,2196,2206,2195,2029,1644,2184,1576,1954,2079,2207,2124,2055,1930,2138,2214,2095,1957,2130,2223,2140,1977,2150,2251,2187,1048,2167,1914,2133,2250,1382,1851,2252,1790,2131,1649,1722,2078,2029,2244,1831,1926,1058,2254,2201,2222"

```

**Comment by az** [comment]
sent

**Comment by klaudia2209** [comment]
great, thank you
