### ISSUE TITLE
(BUG) formatting issue - description of the exhibitors profile

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#44]
Hello @az, 

I got some important feedback from Account Managers.

There is a problem with text formatting in the description of exhibitors. Formatting is visible as a part of the text - the styles doesn't appear (eg. bold text).

Could you check it, when you will be available, please? 

<img width="934" alt="image" src="https://user-images.githubusercontent.com/118257251/208095832-4782b309-3d8f-4661-993b-a59ae611d057.png">

**Comment by az** [comment]
@klaudia2209 i believe it was already discussed with you and/or Peter... we are still in "legacy mode" / "compatibility mode" .... new panel uses MARKDOWN..... old one used HTML.... we will switch front/public page in a few couple of weeks to show markdown (we must investige how much % of exhibitors already update the profile = used markdown)

**Comment by az** [comment]
@klaudia2209 i have created separate issue about some checks to be made ... if we have 90% of exhibitors using HTML (description was created in old panel) and 10% markdown we would need to stay in "legacy mode" and push exhibitors to update their company description.... do you get it and able to pass the info to AM? :)

**Comment by az** [comment]
@klaudia2209 totally btw - if you cannot use "BUG reporting template" so this means this is a (QUESTION) :>

**Comment by klaudia2209** [comment]
Sure, ok. I just don't know what are the consequences of 'double languages' let's say. Probably I can ask another question and the answer may be the same.
