### ISSUE TITLE
(QUESTION) - more VIP links for website testing and adding the translations 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#46]
hello, @az - could you add me more valid links to use them for testing? I'm working on the VIP page and when I want to add the e-mail address I can't go to the form, because the VIP code is expired (I think that I already used them all). I'm working on E-commerce Berlin Expo profile id - 1054 

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/118257251/207894512-5b059003-af68-4502-9b02-f2ae10e67179.png">

**Comment by klaudia2209** [comment]
@az do we have any update about it? Mark would like to send the VIP invitations and I block him now

**Comment by az** [comment]
@klaudia2209 as we discussed it MANY TIMES --- only viplinks sent via panel (via @ ) have expiration.... SO WE OF COURSE DEAL WITH BIG BUG here which i am trying to target.....

**Comment by az** [comment]
@klaudia2209 you can finish the translation process - i have managed to fix VIP registration so the link from EBE account @ account.ecommerceberlin.com are working now :)

**Comment by klaudia2209** [comment]
Thank you so much! 

@az what about this case: 

- I want to check notifications/commands, when I am already register
- I use new link and I click the button 'check the link'
- I put the e-mail - there is a command that 'You have registered already as a VIP' (translation works, I can't fill the form again and it's ok) 
- but if I want to use this link again and for example to send it to someone else - it shows that it's expired 

It's expired even if the form wasn't filled in... Is it ok?

**Comment by klaudia2209** [comment]
There is also another case. 

I register as a visitor from my different e-mail - klaudia.chomiak9@gmail.com 

I use ecommerceberlin.com page, the form on the homepage. 

Then I used the VIP link and type the same e-mail - klaudia.chomiak9@gmail.com it also showed that command that 'I have already registered as a VIP'. 

It looks like all the visitors may have VIP status...? There is no info that I have been upgraded to VIP or sth.

**Comment by klaudia2209** [comment]
I know that you love screenshots, but... ;) 

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/118257251/208874244-7238dfc9-5e5e-4c34-b96b-607f7db2c7a3.png">

**Comment by az** [comment]
what is "command" ? 
(i really dont know why im discussing this but...)
i think that ADMIN PANEL should not verify if the visitor is already a VIP from security-privacy-reasons
who would send 3 invitations to the same person? ONLY A TESTER or a MORON :) what is the case here to talk about? i dont care how exhibitors use it---i care whether they use it or not.

**Comment by klaudia2209** [comment]
command, text, comment... the text which appear after action. 

Ok. Nevermind :) 

But I think that if someone register as visitor and then use the VIP link should see something different than "You have already registered as a VIP'.

**Comment by az** [comment]
re: "3 the same emails" in addition to " security-privacy-reasons" what if some exhibitor wants to send to board assistant 3 different codes for different users in the company? 

**VIP invite recipient EMAIL does not force you to use the same email during visitor-check, visitor-upgrade so you can receive 3 different codes on 1 inbox and then have 3 different users registered ..... its totally flexible**

**Comment by az** [comment]
> But I think that if someone register as visitor and then use the VIP link should see something different than "You have already registered as a VIP'. Edited - ok, I will change the status a bit and it will work.

exactly....re-translate it .... personally i cannot see anything wrong with such info

**Comment by az** [comment]
@klaudia2209 apropos 2 pierwszych komentarzy z dzisiaj .... nie do konca je rozumiem (bo np komenda to dla mnie cos co wpisuje sie w konsoli i ma wykonac jakies zadanie.....) 

mozesz opisac po polsku jesli widzisz jakis blad we flow/dzialaniu? wyjasnimy to i ew. zrobimy osobne taski

**Comment by klaudia2209** [comment]
Ok, komenda to złe słowo, dlatego czasami używałam notification, ale to też nie do końca to. Powiedzmy, że to status (?). 

Zastanawiałam się nad tym kiedy link jest wykorzystany: 
- jak wypełnię formularz i staję się VIPem - ok, wykorzystałam link
- ale jak załóżmy nawet przez przypadek ktoś wpisze jeszcze raz ten sam e-mail, to pojawi się ten status, że już jest VIPem, ale ten link nie może zostać ponownie użyty, bo pojawił się status. A wg mnie skoro nie został wpisany inny adres e-mail, ktoś nie wypełnił formularza, to ten link nadal powinien być aktywny. 

Załóżmy, że ktoś dostaje 3 linki, wpisuje swoich 3 pracowników z pracy i dwa razy wpisze ten sam e-mail. I wtedy właściwie wykorzysta już 2 linki i zostanie mu tylko 1. 

Nie wiem czy to problem, możemy to zostawić, zauważyłam, to daję znać, jak nie ma to znaczenia, to zostawmy jak jest i tyle

**Comment by klaudia2209** [comment]
A co do tego drugiego - to myślę, że wystarczyło inaczej napisać status i wtedy pasuje w obu sytuacjach, więc powinno być ok

**Comment by az** [comment]
@klaudia2209 

wiesz ze filozofowanie z Tobą jest kosztem realnej pracy - jestes tego swiadoma?

ogarnianie tematow jest sztuką kompromisu.....done is better than perfect itp itd
status musi sie pokrywac z tym co mozemy "wykryć" majac ustalona logike dzialania aplikacji... nie zawsze slowny opis rzeczywistosci mozna zrealizowac 1:1 w swiecie IT albo jest to po prostu pozbawione sensu .... tutaj to wynik nastu lat doswiadczenia... junior napierdala wszystko a senior napierdala tam gdzie jest to oplacalne (bo np poswiecasz 3x wiecej czasu a pokrywasz 5% use caseow:)

teraz wymyslilas sobie w glowie 4 statusy i jeden z nich przetlumaczylas tak ze stracil na uniwersalnosci 

jesli KOD jest przeznaczony dla konkretnej osoby (przeciez nie wysylamy go na FB) to jesli czlowiek juz jest VIPem to 
1) dlaczego mialby sie rejestrowac drugi raz na ten sam email ?
2) kod nie powinien byc wazny jesli jednak zajdzie (1)-chcielismy konkretnego czlowieka jako VIPa i go mamy.... ideą tego ficzeru jest zapraszanie KONKRETNYCH ludzi a nie wykorzystywanie kodów :D 

ALE JEST potencjalny BUG....przy (2) powinienem dostac w panelu nowy KOD czyli limit zapek powinien byc liczony nie po przypisanych userach tylko po unikatowych @ odbiorcow zapek ....... ALE jest tutaj zagrozenie ze ktos bedzie wysylal zapki do nazwa+111@firma.pl tym samym nie wyczerpujac limitu

dlatego z tym potencjalnym bugiem niczego nie robie....bo na koniec dnia ma znaczenie ile tych zapek jest wykorzystywanych i pchanie dodatkowej energii w ten temat bedzie zasadne jesli np > 60% wystawcow wykorzysta min 80% zapek a tak nie jest........dlatego teraz focus na sensownosc tlumaczen

ten feature jest tak zaprojektowany zeby pokryl moja wizje VIP...to nie jest rozdawanie cukierkow  :)

**Comment by klaudia2209** [comment]
Ok, napisałam to po polsku, żeby wyjaśnić, co miałam na myśli. W porządku, zaznaczam, że coś zauważyłam, jeśli to nam w niczym nie przeszkadza to zostawmy jak jest. 

Status przetłumaczyłam później w inny sposób i powinno być ok.
