### ISSUE TITLE
(E-MAIL) Christmas wishes 2023 - to send 22.12.2023 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#47]
Hello, @az could you send the Christmas wishes to the exhibitors, please? I know that it's late a bit, but last week I forgot to add the content, I am sorry. 

If you may send it, please send the e-mails as DK, AO, MB. We would like to send it on Thursday. We will assign proper AM on Thursday morning. 
_______________

ENGLISH: 

**Subject:** Season’s greetings from the very merry team at E-commerce Berlin Expo!

In the midst of the holiday season, we find ourselves reflecting on the past year and those who have helped shape our company. The end of the year brings no greater joy than the opportunity to express our sincere appreciation for the trust you have placed in us.

It’s been quite a year! We hope that 2022 has been just as memorable for you, your colleagues, and your loved ones. We look forward to working with you in the months to come.

Wishing you a season of joy and looking forward to continued success in the future. Let’s make 2023 even better!

Warmest greetings
E-commerce Berlin Expo Team

**Comment by az** [comment]
@klaudia2209 i think xmas wishes in BUSINESS (not family) context i so fucking idiotic idea (its polluting) so i totally refuse to send it. Please focus on exhibitors future conversion from  the trade fair - they really fuck the rest.
( will inform Marek and Peter that i cannot proceed with that)
