### ISSUE TITLE
(QUESTIONS) - company representatives - error vs. 2 weeks before the event 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#48]
Hello, @az 

exhibitors sends questions about the company representatives - they think that they can already add them and send us questions why errors appear. 

Several questions regarding to that: 

1) can we remove "register company representatives" from the 1st step on the timeline? (if they can do this only 2 weeks before, I believe that we don't need that there) 

2) what would be the best option to remove this inconvenience? 
- make this subpage invisible
- add some pop-up with info that this section will be available 2 weeks before the events

3) the translation of the words doesn't work, I don't know why (but it's a separate topic)

<img width="988" alt="image" src="https://user-images.githubusercontent.com/118257251/208616379-0e56c186-c3a6-4d21-9a18-297bb518ce28.png">

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/118257251/208617138-90773cb7-554a-43b2-951c-8184f7b80f60.png">

**Comment by az** [comment]
@klaudia2209 if that is visible in the menu it means we wanted to show it.....so this is the BUG (ticket misconfiguration in the old admin)....i have now fixed that - exhibitors CAN register their reps now

**Comment by az** [comment]
in such cases i just need the info "representatives registration does not work" i dont need screenshots and long descriptions as i know where it is and how that works and this kind of behaviour (you cannot register) i self-explanatory :)

**Comment by klaudia2209** [comment]
I heard that exhibitors will do that 2 weeks before the event and it's not needed for now, so because of that I was thinking about turning off this functionality for now; 

It works, I checked, thank you

**Comment by az** [comment]
one thing is ENABLING and the other is COMMUNICATING.... 

i am sure if it was revealed from the beginning and Peter saw this 2 months ago it should stay revealed

you will communicate / push exhibitors to fill in whatever time you want - i believe 2 weeks to the event is the DEADLINE as IDs must be sent to the printing house then....

**Comment by klaudia2209** [comment]
I talked about it to AM, so probably I got wrong information. I also prefer when things are available earlier. 

Anyway - it's good that it's clarified and it works now.
