### ISSUE TITLE
(TRANSLATION) translate company reps form

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#49]
![E-commerce Berlin Expo 2022-12-20 09-51-37](https://user-images.githubusercontent.com/2198/208624588-b206cedf-7723-4914-98b4-ecba81d46512.jpg)

some form input fields seem not translated

* profile.fname
* profile.lname
* profile.position
* profile.phone

please make it translated

**Comment by klaudia2209** [comment]
They are translated in loco, but there is something wrong with them, I don't know why they don't want to appear

**Comment by az** [comment]
@klaudia2209 i will check it out

**Comment by klaudia2209** [comment]
thank you
