### ISSUE TITLE
(TRANSLATION) promo materials 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#51]
as seen here - https://account.ecommerceberlin.com/#/promote?company_id=1054

**Comment by az** [comment]
@klaudia2209 

podglad wersji EN (przegladarka w trybie incognito) -https://account.targiehandlu.pl/#/promote?company_id=2144

**Comment by klaudia2209** [comment]
English translation added to english and german version. 

German translation will be added next week

**Comment by klaudia2209** [comment]
done
