### ISSUE TITLE
BANNERS for promo materials feature

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#52]
as seen here https://account.ecommerceberlin.com/#/promote?company_id=1054

dimensions 

* 1920x1080
* 1080x1080
* 468x60
* 336x280
* 300x250
* 728x90
* 250x250

każda kreacja musi mieć miejsce na numer stoiska.......odpowiedniej wielkości (np A9.5)

**Comment by klaudia2209** [comment]
@az great, could you tell me in which format these materials should be? .eps, .psd, .png? I informed PR team about it

**Comment by az** [comment]
@klaudia2209 PNG

**Comment by az** [comment]
@klaudia2209 no jasne, ze automatycznie. 
wielkosc info dot stoiska moge skalowac (w sensie czcionke) wiec tym sie nie kierujcie....jedynie trzeba miec swiadomosc ze sa nr stoisk np A9.5 i one sie musza zmiescic wiec BIAŁY BOX musi byc w miare szeroki

**Comment by klaudia2209** [comment]
super, zrozumiano, dzięki! ;)

**Comment by klaudia2209** [comment]
Hej, podsyłam link do grafik do google drive na slacku.

**Comment by az** [comment]
https://drive.google.com/drive/u/3/folders/11yMkRwo0nCIJsVhSh_PSMcmPHE3w-OZY
