### ISSUE TITLE
(TRANSLATION/UPDATE)  promo materials / emails

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#54]
szablony kampanii email dla wystawcy (en i de)

trzeba zaktualizować treść (pewnie musisz podpytać Marka o przykłady firm....chyba że to nie ma większego znaczenia)

https://services.eventjuicer.com/api/company-newsletters/1?participant_id=163172&dl=1
https://services.eventjuicer.com/api/company-newsletters/2?participant_id=163172&dl=1

/każdy język jako osobny komentarz - bez mieszania wszystkiego w 1 komentarzu /

**Comment by klaudia2209** [comment]
**ENGLISH**

Hi,

We would like to let you know that we are exhibiting at the E-Commerce Berlin Expo 2023 which will take place on 23rd of February at STATION Berlin, Luckenwalder Str. 4-6.

Please consider this email your personal invitation from us. We hope to see you at our booth during the Expo!

Why should you visit?

All the major decision-makers from digital commerce, marketing, and innovation come together at E-commerce Berlin Expo for a one-of-a-kind networking experience.

Over 250 companies will exhibit and over 70 leading experts from giants such as Borussia Dortmund, Zalando, Meta, OMIO, eBay, EVENTIM, Mercedes-Benz Cars, Paul Hewitt, Amorelie, Farfetch and Thomann.io, will present innovative and forward-looking developments and trends to will help you find new opportunities to grow your e-commerce business.

E-commerce Berlin Expo enables you to connect with other like-minded individuals striving for success, find partnerships that will last for years, as well as expand your knowledge and skillset to stay ahead of the competition.

Sounds good?

You can register for the full day of networking, dialogue, education, and inspiration - and all that completely free of charge! All you have to do is register in advance on the official website of the event.

Get your free ticket now and stop by our stand to chat with us - click here to register: 

<link> https://ecommerceberlin.com/visit?utm_source=email&utm_medium=email&utm_campaign=promo_ninja

If you haven't seen the full agenda yet, check it out here: [https://ecommerceberlin.com/schedule](https://ecommerceberlin.com/schedule?utm_source=email&utm_medium=email&utm_campaign=promo_ninja)

Join us for an unforgettable experience that will take your business to the next level!

We’re looking forward to meeting you! 

Kind regards

**Comment by klaudia2209** [comment]
**GERMAN**

Hallo,

Wir freuen uns, Dir mitteilen zu können, dass wir als Aussteller auf der E-Commerce Berlin Expo 2023 auch mit dabei sind und wollen Dich einladen, uns am 23. Februar in der STATION Berlin, Luckenwalder Str. 4-6 persönlich zu besuchen.

Mit dieser E-Mail wollen wir Dich persönlich zum Besuch einladen. Wir hoffen, dich an unserem Stand auf der Expo zu sehen!
 
**Warum ein Besuch bei uns lohnt?**

Auf der E-Commerce Berlin Expo treffen sich alle wichtigen Entscheidungsträger aus den Bereichen E-Commerce, Marketing und Innovation zu einem einmaligen Networking-Erlebnis.

Über 250 Unternehmen stellen aus und mehr als 70 führende Experten von Branchenriesen wie Borussia Dortmund, Zalando, Meta, OMIO, eBay, EVENTIM, Mercedes-Benz Cars, Paul Hewitt, Amorelie, Farfetch und Thomann.io präsentieren innovative und zukunftsweisende Entwicklungen und Trends, die dir helfen werden, neue Möglichkeiten für das Wachstum deines Onlinegeschäfts zu finden.

Die E-Commerce Berlin Expo bietet die Chance, mit Gleichgesinnten in Kontakt zu treten, die nach Erfolg streben, langfristige Partnerschaften zu schließen und das eigene Wissen und Können zu erweitern, um der Konkurrenz einen Schritt voraus zu sein.

**Klingt gut?**

Melde dich für den ganzen Tag voller Networking, Dialog, Bildung und Inspiration an - und das alles völlig **kostenlos!** Alles, was du tun musst, ist, dich im Voraus auf der offiziellen Website des Events zu registrieren.

Sichere dir jetzt dein **kostenloses Ticket** und komm an unserem Stand vorbei, um sich mit uns zu unterhalten - **hier geht's zur Anmeldung:**  

<link> (https://ecommerceberlin.com/visit?utm_source=email&utm_medium=email&utm_campaign=promo_ninja)

Wenn du das vollständige Programm noch nicht kennst, kannst du es hier ansehen: (https://ecommerceberlin.com/schedule) **podmieniony na:** (https://ecommerceberlin.com/schedule?utm_source=email&utm_medium=email&utm_campaign=promo_ninja)

Komm und erlebe mit uns ein unvergessliches Abenteuer, das dein Unternehmen auf die nächste Stufe bringt!

Wir freuen uns auf die Begegnung mit Dir! 

Schöne Grüße
