### ISSUE TITLE
confirm promoninja PRIZES 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#55]
@klaudia2209 discuss with @peterecommberlin what we cancel or what we add in "promoninja" contents for exhibitors

**Comment by klaudia2209** [comment]
Hej! 

Mam potwierdzone nagrody z Piotrem. Chcemy dać termin zakończenia konkursu na 20.02 - żeby pierwsze miejsce mogło się przygotować na wywiad, firmy wzięły roll-upy ze sobą i żeby to wcześniej sprawdzić. 

- wywiad video (tylko dla 1st place)
- dedykowaną pulę sprzedaży
- mega pakiet zaproszeń
- wyróżnienie logotypu
- roll-up poza stoiskiem
- rozdawanie ulotek
- artykuł na EGN

UWAGA! NIE DAJEMY WIECEJ PREZKI

**Comment by az** [comment]
@klaudia2209 cool... re prezka - jasne.

**Comment by klaudia2209** [comment]
zmieniłam punktację w dwóch miejscach
