### ISSUE TITLE
promoninja - remove old/legacy tracking UTMs  

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#56]

**Comment by klaudia2209** [comment]
Mam pytanie - czy to odnosi się do tego, że wystawcy już zdobywają punkty w promoninja? Rozumiem, że zerujemy te punkty i zaczynają je zdobywać od wystartowania z konkursem, tak? ;)

**Comment by az** [comment]
hej

nie moge na kazdy temat dyskutowac bo robilbym to w wielu przypadkach po
raz 15

task dla mnie - wiec o co w nim chodzi
-- 
Regards / Pozdrawiam,

Adam Zygadlewicz

mobile: +48 605 501 601
skype: adam.zygadlewicz
http://fb.me/adam.zygadlewicz
http://twitter.com/az
