### ISSUE TITLE
(E-MAIL) adding contacts in the exhibitors' platform - PR / sales / event manager 05.01.23

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#57]
Hello @az, 

We would like to send reminder to exhibitors about adding contact person (pr / sales / event manager) 

I have few questions about next e-mail: 
1) Is it possible to send it on 05.01.23 (or earlier)? 
2) Can we exclude people who already added contact? 
3) Can we add the button "Click here to add contacts"? 
4) We would like to send e-mails as DK, AB, AO
______________

**ENGLISH**

SUBJECT: Add your contacts to stay up to date | EBE 2023

To improve our communication and to ensure that our messages reach the responsible people on your side in the future, we would like to ask you in this email to kindly fill in the contact section on the exhibitor platform and add your company’s employees.

Kindly add, if possible:
- PR Manager
- Event manager
- Sales Manager

This will keep you up to date with future topics concerning, for example, pre-sales, collaboration, event organisation and cooperation offers.

BUTTON **CLICK HERE TO ADD CONTACTS** (https://account.ecommerceberlin.com/#/people/create)

Should you have any questions, please let me know. 

Best regards,
XXX

**Comment by klaudia2209** [comment]
GERMAN 

Topic: Füge Kontakte aus deinem Unternehmen hinzu, um auf dem Laufenden zu bleiben | EBE23

Um in Zukunft unsere Kommunikation noch zu verbessern und sicherzustellen, dass unsere Nachrichten die zuständigen Personen auf Eurer Seite erreichen, möchten wir Dich in dieser E-Mail bitten, den Kontaktteil auf der Ausstellerplattform auszufüllen und die Mitarbeiter Deines Unternehmens anzugeben.

Bitte nach Möglichkeit hinzufügen:
- PR-Manager
- Event-Manager
- Sales-Manager

So werdet ihr in Zukunft über Themen wie z.B. Vorverkauf, Zusammenarbeit, Veranstaltungsorganisation und Kooperationsangebote auf dem Laufenden gehalten.

BUTTON **KLICKE HIER, UM KONTAKTE HINZUZUFÜGEN**

Bei Fragen lass es mich bitte wissen.

Beste Grüße,
XXX

**Comment by az** [comment]
ma to ograniczony sens bo to nie jest jeszcze wykorzystywane - jest przy
okazji / „for future use”

1. 5/01 realny
2. na ten moment nie
3,4 - nie powtarzaj tego all the time prosze :)
zawsze daje button kontekstowy i zawsze wysylka idzie wg przyposan AM o ile
przed wysylka bedzie przeprocesowana CHECKLISTa dot wysylki—— kto ja
ogarnie?

-- 
Regards / Pozdrawiam,

Adam Zygadlewicz

mobile: +48 605 501 601
skype: adam.zygadlewicz
http://fb.me/adam.zygadlewicz
http://twitter.com/az

**Comment by klaudia2209** [comment]
myślisz w takim razie, że nie warto go wysyłać? 

1. ok
2. ok 
3,4 - ok, Peter zawsze przydziela AM przed wysyłką @peterecommberlin

**Comment by az** [comment]
@klaudia2209 mysle, ze sens jest ograniczony. lepiej wyslac cos ala "sprawdz swoj profil - bo mamy wyszukiwarke" albo oficjalnie puscic promoninja (tutaj ja musze sie wyrobic + trzeba potwierdzic nagrody)

**Comment by klaudia2209** [comment]
a z tym sprawdzeniem profili i wyszukiwarką - o co dokładnie chodzi? co mają sprawdzić i gdzie? 

promoninja chcieliśmy puścić w kolejnym tyg, bo jeszcze pracujemy nad treścią 

nagrody potwierdzone tutaj: 
https://github.com/ecommerceberlin/exhibitors/issues/55

**Comment by az** [comment]
@klaudia2209 swoj profil.... publiczny profil wystawcy .... maja "company data" czyli edycje danych i moga sobie zobaczyc jak to wyglada

nagrody - odpowiedzialem wiec zauwazylem.

zmienilismy komunikacje na jezyk polski ale widze ze nadal mamy z nia problem.

**Comment by klaudia2209** [comment]
O edycji danych AM komunikują bezpośrednio wystawców 

prośba o zostanie przy tej propozycji maila, bo mam info od AM, że im się to akurat przyda

**Comment by az** [comment]
jasne - pod katem danych dla AM to ma to sens 

"O edycji danych AM komunikują bezpośrednio wystawców" - o mozliwosci tak...natomiast AM nie dysponuja automatem ktory sprawdza co masz nieoptymalne i co powinienes poprawic

benchmarkiem ("O edycji danych AM komunikują bezpośrednio wystawców") jest chocby zmiana opisu firmy / przeformatowanie pod katem html->markdown - o tym komunikuja? jesli tak to zawnioskuje o nagrode.
