### ISSUE TITLE
(QUESTION) - active promoninja ranking

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#58]
Hi, 

I have a question - what will we do with the current promoninja ranking? Will we reset it and start ranking with the date of the competition?

**Comment by az** [comment]
@klaudia2209 na co takie pytania? jakie to ma znaczenie jak to bedzie to zresetowane? idziesz w kierunku programowania?

**Comment by klaudia2209** [comment]
:D Nie, Adam, to po prostu pytanie od Piotra, które Tobie przekazałam :)

**Comment by az** [comment]
@klaudia2209 ale sposob zadawania tych pytan jest co najmniej zagadkowy - jak bys totalnie nie wiedziala o co pytasz. 
prosilem juz wiele razy zebys formulowala tematy w sposob problemowy (jesli nie potrafisz to znaczy ze nie ma tematu) - ja nie mam czasu na tzw publicystyke....

przyklad juz mielismy...... zamiast zapytac jak organizator warsztatów moze sie zarejestrować (co byc moze wzbudziło by moja czujnosc i wskazalbym na potrzebe skonczenia strony masterclasses) to zadalas pytania "jak dodawac tickety do admina"... nie widzisz tutaj problemu? :)

tutaj podobny kejs..... jesli nie ufasz mojej inteligencji to dodaj pseudo taska "nie zapomnij o resecie" ale pytanie co sie stanie z obecnym rankingiem?  te pytania są po prostu idiotyczne, Klaudia.

**Comment by klaudia2209** [comment]
NIe wiem co mam Ci odpowiedzieć. Niektóre pytania przekazuję, żeby mieć pewność, że rozwiałam czyjeś wątpliwości. Ja też poświęcam czas na rozmawianie z osobami z firmy, żeby dobrze sprecyzować to, o co chcę zapytać, ale w przypadku pytań Piotra (który ma X stażu w firmie i wie o co pyta) o ranking albo o tickety - założyłam, może błędnie, że wystarczy jak będę przekaźnikiem, a nie analitykiem pytania. 

W tym przypadku wystarczyłoby - tak, wyzeruję ranking i koniec tematu. 

Nie podważam czyjejś inteligencji.
