### ISSUE TITLE
(BUG) Masterclasses' speakers data not visible, severals sections are not visible when we want to edit data

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#59]
**title**
Not visible all masterclasses' speakeres data or/and particular sections are not visible when we want to edit 

environment (chrome/safari/firefox/msie, etc)
firefox/chrome 
showing data, possibility of editing data
 
actual result
firefox - not every data visible (Fabien) 
chrome - data visible 
Edit - sections dissapear, eg. description, **there is no possibility to edit data**

steps to reproduce
example: 
masterclasses' speakers - Chen Zissu speaker - view profile - edit profile - some of the data is hidden

Severity/Priority
Critical (blocking) - it may block our work when we want to edit some data

number of users already affected (reporting this issue) of total users
2

team members who tested (apart from creator of bug report)
me, Fabien

**Comment by az** [comment]
@klaudia2209 tylko pola profilowe ktore zostaly przypisane do ticketa sa edytowalne - wiec to nie bug tylko brak konfiguracji - 

a przypisuje sie tutaj - https://pages.ecommerceberlin.com/admin/assigninputs zarowno PSZ jak i MT na pewno wytlumacza jak to zrobic
