### ISSUE TITLE
(TRANSLATION) translate participant-to-exhbitor meetups 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#69]
![E-commerce Berlin Expo 2023-01-11 12-24-56](https://user-images.githubusercontent.com/2198/211805936-cfc566e0-acc9-4681-a9d2-d0e572470165.jpg)

pytasz o mnie o filozoficzne pierdoly typu "co sie stanie z rankingiem" a nie konczysz tematu ktory ewidentnie dotykasz @klaudia2209 ... dla mnie taka formula wspolpracy to utrapienie :)

**Comment by klaudia2209** [comment]
zrobione
