### ISSUE TITLE
(TRANSLATION) email meetup (participant-to-company) accepted 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#72]
![Masz spotkanie z Wystawcą  i status VIP  Your meeting with the exhibitor is now confirmed  - adam zygadlewicz@gmail com - Gma… 2023-01-11 12-34-19](https://user-images.githubusercontent.com/2198/211807573-51713f44-752e-4ad5-bf71-0f77e27393c1.png)

**Comment by az** [comment]
@klaudia2209 dodalem jakies temp gowno zeby nie przedluzac

**Comment by klaudia2209** [comment]
Ok, jak coś to ustaliliśmy, że osoba z meeting request nie otrzymuje statusu VIP i że się spotykają na stoisku. Przygotujemy treść.

**Comment by klaudia2209** [comment]
Treść po angielsku i niemiecku w jednym mailu: 

Subject: Your meeting with the exhibitor is confirmed | EBE 2O23 

Hello XXX,

YYY has accepted your invitation to a booth meeting.

The exhibitor now has your contact details (email and phone).

See you then!
____________

Hallo XXX,

YYY hat deine Einladung zu einem Standtreffen angenommen.

Der Aussteller hat nun deine Kontaktdaten (E-Mail und Telefon).

Bis dann!

**Comment by az** [comment]
> Ok, jak coś to ustaliliśmy, że osoba z meeting request nie otrzymuje statusu VIP i że się spotykają na stoisku. Przygotujemy treść.

na pewno widzisz w potwierdzeniu tymczasowym, ze takiego info nie dalem....
