### ISSUE TITLE
(TRANSLATION) finalize promote translation

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#77]
gdybys przeklikala te 5 profili z innego issue to bys zobaczyla ze nie wszystko jest przetlumaczone 

![E-commerce Berlin Expo 2023-01-13 16-21-18](https://user-images.githubusercontent.com/2198/212368771-1b44b1b9-5947-47f4-afaa-9f58a0b5c7ba.jpg)

**Comment by klaudia2209** [comment]
Done by Peter
