### ISSUE TITLE
(TRANSLATION/EMAIL) P2C invitations

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#79]

**Comment by az** [comment]
```

@component('mail::message')
 
# Cześć {{ array_get($profile, "fname")  }},

[Na Twoim publicznym profilu Wystawcy]({!! $trackingLink !!}) pojawiła się nowa funkcjonalność "UMÓW SIĘ NA SPOTKANIE".

**Zwiedzający mogą być inicjatorami spotkania z Tobą** aby jeszcze przed dniem targowym nawiązać z Tobą komunikację

## Jak to działa? 

Kiedy promujesz swoje uczestnictwo w Targach (zapraszamy do korzystania z przygotowanych dla Ciebie materiałów promocyjnych) i kierujesz Internautów do swojego profilu Wystawcy mogą oni wypełnić prośbę o spotkanie.

Wszystkie zaproszenia od Zwiedzających lądują w zakładce **RSVPs** w Panelu Wystawcy  (będziemy także Cię powiadamiać o oczekujących zaproszeniach)

Potwierdzając chęć spotkania **otrzymujesz natychmiastowy dostęp do danych kontaktowych Zwiedzającego**

## Jak promować swój profil Wystawcy i funkcję umawiania się na spotkanie?

Użyj [strony z gotowymi materiałami dla Twojej firmy]({!! $accountUrlPromote !!}) lub promuj się tak jak chcesz z wykorzystaniem Twojego URLa - {!! $trackingLink !!}

Pamiętaj, że strona z materiałami promocyjnym jest publiczna. Adres [URL do tej strony]({!! $accountUrlPromote !!}) możesz skopiowac z paska adresu przeglądarki i wysłać osobie odpowiedzialnej za działania reklamowe w firmie.


Regards, 

{{$footer}}

@endcomponent


```

**Comment by az** [comment]
potrzebuje tlumaczen EN i DE na srode 18.01

**Comment by klaudia2209** [comment]
ENGLISH: 
SUBJECT: Working on it  

@component('mail::message')

# Hi {{ array_get($profile, "fname")  }},

[On your public Exhibitor profile]({!! $trackingLink !!}) a new feature "REQUEST A MEETING" has been launched.

**Visitors can be the initiator of a meeting with your company** to establish communication with you even before the trade fair day.

## How does this work? 

When you promote your participation in the EXPO (a gentle reminder: you can use promotional materials provided by us) and you send the link to your Exhibitor’s public profile to the visitors - they can arrange a meeting with you by clicking “REQUEST A MEETING” 

All invitations from Visitors land in the **RSVPs** tab on the Exhibitor Platform (we will also notify you of pending invitations).

By confirming an appointment **you get instant access to the visitor’s contact details**.

## How do I promote my Exhibitor profile and appointment function?

Use [a section with ready-made materials for your company]({!! $accountUrlPromote !!}) or promote yourself as you wish using your URL - {!! $trackingLink !!} 

Please note that the promotional material section of the website is public. You can copy the address [URL to this page]({!! $accountUrlPromote !!}) from the address bar of your browser and send it to the person responsible for your company's advertising activities.

Regards, 

{{$footer}}

@endcomponent

**Comment by klaudia2209** [comment]
GERMAN: 

Subject: working on it

@component('mail::message')

# Hallo

[Auf deinem öffentlichen Ausstellerprofil]({!! $trackingLink !!}) wurde eine neue Funktion "REQUEST A MEETING" eingeführt.

**Besucher können dein Unternehmen zu einem Treffen einladen**, um schon vor dem Messetag mit euch Kontakt aufzunehmen.

## Wie funktioniert das?

Wenn du für deine Teilnahme an der EXPO wirbst (zur Erinnerung: du kannst von uns zur Verfügung gestelltes Werbematerial verwenden) und den Link zu deinem öffentlichen Ausstellerprofil an die Besucher schickst, können diese ein Treffen mit euch vereinbaren, indem sie auf "REQUEST A MEETING" klicken. 

Alle Einladungen von Besuchern landen in der **RSVPs** auf der Ausstellerplattform (über ausstehende Einladungen werden wir dich ebenfalls informieren).

Wenn du einen Termin bestätigst, **erhältst du sofortigen Zugang zu den Kontaktdaten des Besuchers**.

## Wie kann ich mein Ausstellerprofil und meine Terminfunktion promoten?

Nutze den [Teil mit vorgefertigten Materialien für dein Unternehmen auf der Austtellerplatform]({!! $accountUrlPromote !!}) oder werbe mit deinem eigenen URL - {!! $trackingLink !!}

Bitte beachte, dass der Teil mit dem Werbematerial auf der Website öffentlich ist. Kopiere die Adresse [URL zu dieser Seite]({!! $accountUrlPromote !!}) aus der Adresszeile deines Browsers und schicke sie an die Person, die für die Werbemaßnahmen in deiner Firma zuständig ist.

Viele Grüße, 

{{$footer}}

@endcomponent
