### ISSUE TITLE
(BUG) RVPS mixed with Przeglądaj uczestników

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#81]

**Comment by az** [comment]
![E-commerce Berlin Expo 2023-01-17 21-46-48](https://user-images.githubusercontent.com/2198/213019417-25742386-0e11-4437-9cb7-3abb8a26200e.jpg)

ADD usuniete @klaudia2209 ... issue dot zmiany tlumaczenia strony welcome/empty results dla meetups czeka i sie usmiecha do Ciebie
