### ISSUE TITLE
(TRANSLATION) make RSVP welcome/empty screen more universal (not referencing CP2 meetups)

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#83]
![E-commerce Berlin Expo 2023-01-17 21-26-03](https://user-images.githubusercontent.com/2198/213015776-2e9cb50a-7de9-43c1-aab4-78f9a6304362.jpg)

czyli trzeba to przetlumaczyc na cos ala "tutaj znajdziesz wszystkie wyslane i otrzymane zaproszenia" i to ladnie opisac jak to dziala....

**Comment by klaudia2209** [comment]
tylko chodzi o to, że jak już ktoś ma zaproszenia, to nie może wrócić z powrotem do listy wszystkich visitorsów... widok z listą wszystkich zaproszeń jest "jednorazowy" do momentu wysłania/otrzymania 1 zaproszenia, później już go nie ma i nie ma też zakładki "browse visitors". Więc wystawcy będą się zastanawiać jak wrócić do widoku z listą wszystkich osób (już padło takie pytanie)

**Comment by az** [comment]
@klaudia2209 

naucz sie systemu i timeline - powtarzam to po raz 10x

![E-commerce Berlin Expo 2023-01-18 09-52-29](https://user-images.githubusercontent.com/2198/213139998-6b0ed809-b0dd-4c71-94ea-49141c2218c0.jpg)

zgodnie z timeline dotep do visitorsow ma byc za 2 tygodnie i zgodnie z widokiem w account na koncie EBE jest to ukryte
wiec nikt nie ma tam wchodzic......a jak bedzie mial wchodzic to bedzie mial pozycje w menu

wszedl teraz przypadkowo przez JEDNORAZOWY widok pustych zapek bo ta sekcja kiedys sluzyla tylko do visitorsow (zapek C2P) a teraz sluzy do 3 typow zapek (CP2, P2C i zapisow limitowanych)

nie ucz ojca robic dzieci.... po raz ostatni prosze o to byc sie nauczyla account i timeline

**Comment by KarolinaTEH** [comment]
You can manage your invitations in this tab. 

*Tip*: There are useful filters above the list.

**Invitations received from Visitors**

Visitors can send you invitations for a meeting during the event.

Once you accept the invitation, Visitor's contact details will be visible here. From this point you can arrange the meeting through your own channels.

Make sure you have defined *Sales Manager* in the *Company -> Contact* tab. Sales managers receive notifications about new invitations.

**Invitations sent by you**

After sending your invitation, the selected participant receives an email where it can be either accepted or rejected. The thumb up in the *Status* section means an accepted invitation, and the timer - pending invitation.

Once your invitation gets accepted, the contact details of the invited person will be visible here. From this point you can take over and complete the appointment through your own channels.

If you can see the *Delete* button, it means that your invitation has not been sent yet and you can cancel it (and invite someone else instead).

@klaudia2209 możesz użyć tego
