### ISSUE TITLE
(TRANSLATION) masterclasses RSVP 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/exhibitors#84]
skoro jest na Twoim screenie i testowalas to zapewne przetlumaczylas ale na wszelki wypadek potwierdz 

**resources.meetups.ltd**

https://user-images.githubusercontent.com/118257251/212921589-de69b631-0bb3-4ae9-96e6-c1be57f705ef.png

**Comment by klaudia2209** [comment]
przetłumaczyłam na Masterclass participant, czy to ok?
