### ISSUE TITLE
(BUG) PROMO MATERIALS - wrong banners appear

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/exhibitors#85]
Jak testowałam profile i sprawdzałam bannery to było ok, ale teraz widzimy, że pojawiają się stare grafiki z 2022 po udostępnieniu profili... :( 

<img width="559" alt="image" src="https://user-images.githubusercontent.com/118257251/213148113-3e83946d-928a-402f-aab3-1ec91f4eeef0.png">

**Comment by az** [comment]
related https://github.com/ecommerceberlin/ecommerceberlin.com/issues/282
