### ISSUE TITLE
(BUG) not translated sign-by-email message 

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#86]
@az wystawca dostał maila ze screena. Najbardziej prawdopodobny scenariusz jest taki, że dostał go po otrzymaniu zapki P2C 
case zgłosiło AcitveAnts - nie byli nigdy na TEH, więc nie ma opcji, że weszli do panelu i kliknęli 'zaloguj się' 

![image](https://user-images.githubusercontent.com/80756258/213243246-ac593cd2-7160-4b5f-b742-2966af2c590e.png)

**Comment by az** [comment]
repo ebe a tekst o tehu - tutaj sie gubie
taki mejl idzie jak chcesz sie zalogowac do panelu a nie masz tokena i wysylasz sobie na email token

**Comment by KarolinaTEH** [comment]
jest to case z EBE - takiego maila dostał wystawca z EBE, którego nigdy nie było na TEH

_taki mejl idzie jak chcesz sie zalogowac do panelu a nie masz tokena i wysylasz sobie na email token_ - tak, wiem. 
Wygląda to tak, jakby była podpięta zła treść do powiadomień o zapkach P2C

**Comment by az** [comment]
Klaudia chyba testowala zapki p2c - mozesz zatem je przetestowac one more time? trzeba na koncie innym niz ebe bo jak wystawca nie ma id stoiska to sie nie pokazuje button

**Comment by az** [comment]
@KarolinaTEH tak to template ktory idzie przy logowaniu ..... po prostu nie bylo wersji EN/EBE
jesli koles sie nie logowal to moze ktos za niego....bo dziala to tak ze moze inna osoba z innym @ o ile ten mejl jest z tej samej domeny co wystawca....

tworze issue dotyczacy @ logujacego w wersji EN a to zamykam..... nie ma podstaw zeby sadzic ze to cos ma cokolwiek wspolnego z zapkami P2C (tam nie idzie w ogole powiadomienie ze masz je ogarnac o ile ja recznie tego nie wysle....)
