### ISSUE TITLE
(MAINTENANCE) lower the number of base C2P invites

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#92]
@az

**Comment by az** [comment]
@KarolinaTEH obnizylem do 10...jak na TEHu

**Comment by az** [comment]
@KarolinaTEH sprawdz prosze czy AM team wie jak to dziala

bazowo 10
zrob cokolwiek i zbierz marne 20 pkt z profilu - masz +50

rob wiecej i masz 50 za kazde kolejne 50

max to 200

**Comment by KarolinaTEH** [comment]
prześledziłam wczoraj z Dominikiem panel krok po kroku, więc wszystko powinno być jasne. 
zrobiłam jeszcze przed momentem podsumowanie dot. zapek

**Comment by az** [comment]
@KarolinaTEH rewelacja. dziękuję!
