### ISSUE TITLE
(MAINTENANCE) lower the number of C2P notifications for visitors

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/exhibitors#93]
@az zmniejszenie liczby wysylek do visitorsa do konkretnych dni tygodnia  /raz dziennie

**Comment by az** [comment]
@KarolinaTEH 
![GitHub Desktop 2023-01-25 12-08-43](https://user-images.githubusercontent.com/2198/214548173-c067f20d-c614-443c-aa85-0592a2faf945.jpg)
